### PR TITLE
Debian uses group 42 shadow

### LINKED ISSUE #31: Debian uses group 42 ('shadow') as group for shadow files
This is just as secure as using root, but is currently failing the test.

### PR DESCRIPTION
**Pull request by timstoop**
Fixes #31 (this time actually tested...)

### CODE REVIEW

File: controls/6_1_system_file_permissions.rb [hunk 1]
```diff
@@ -90,11 +90,19 @@
       it { should_not be_writable.by 'other' }
       it { should_not be_executable.by 'other' }
       its(:uid) { should cmp 0 }
-      its(:gid) { should cmp 0 }
       its(:sticky) { should equal false }
       its(:suid) { should equal false }
       its(:sgid) { should equal false }
     end
+    if os.debian?
```
Comment (chris-rock) [inline controls/6_1_system_file_permissions.rb]: I think we can make the test more readable if we do the following instead:

```
expected_gid = 0
expected_gid = 42 if os.debian?
shadow_files.each do |f|
     describe file(f) do
       ...
       its(:gid) { should cmp expected_gid }
```

Comment (timstoop) [reply controls/6_1_system_file_permissions.rb]: Honestly, I'm not very good at Ruby (I'm more a Python guy), so any advice here is appreciated! I'll make the change and push it.
